argocd:
  username: ${ARGOCD_ADMIN_USER}
  password: ${ARGOCD_ADMIN_PASSWORD}
  baseUrl: ${ARGOCD_SERVER}
  appLocatorMethods:
    - type: config
      instances:
        - name: ${ARGOCD_NAME}
          url: ${ARGOCD_SERVER}
